// Difficulty → grid size mapping
export const DIFFICULTY_CONFIG = {
  quick:  { cols: 4, pairs: 6,  label: 'Quick',  grid: '4×3', time: 45,  turnTime: 8  },
  easy:   { cols: 4, pairs: 8,  label: 'Easy',   grid: '4×4', time: 90,  turnTime: 10 },
  medium: { cols: 6, pairs: 18, label: 'Medium', grid: '6×6', time: 150, turnTime: 10 },
  hard:   { cols: 8, pairs: 32, label: 'Hard',   grid: '8×8', time: 240, turnTime: 10 },
  master: { cols: 10, pairs: 40, label: 'Master', grid: '10×8', time: 300, turnTime: 12 },
};

export const GAME_MODES = {
  classic: {
    key: 'classic',
    icon: '🎯',
    name: 'Classic',
    desc: 'Standard memory match rules',
  },
  blitz: {
    key: 'blitz',
    icon: '⚡',
    name: 'Speed Blitz',
    desc: '30s start (+4s per match, -2s miss penalty)',
  },
  combo: {
    key: 'combo',
    icon: '🔥',
    name: 'Combo Streak',
    desc: 'Consecutive matches earn 1x, 2x, 4x points',
  },
  flash: {
    key: 'flash',
    icon: '👁️',
    name: 'Flash Peek',
    desc: 'All cards revealed for 3s at start',
  },
};

export const THEMES = {
  classic: {
    key: 'classic',
    name: 'Mystic Duel',
    icon: '💎',
    cardBack: '✨',
    color: 'var(--accent)',
    glow: 'var(--accent-glow)',
    border: 'rgba(124,106,245,0.45)',
    symbols: [
      { id: 'moon', emoji: '🌙', label: 'Moon' },
      { id: 'star', emoji: '⭐', label: 'Star' },
      { id: 'fire', emoji: '🔥', label: 'Fire' },
      { id: 'flower', emoji: '🌸', label: 'Flower' },
      { id: 'gem', emoji: '💎', label: 'Gem' },
      { id: 'thunder', emoji: '⚡', label: 'Thunder' },
      { id: 'wave', emoji: '🌊', label: 'Wave' },
      { id: 'comet', emoji: '☄️', label: 'Comet' },
      { id: 'planet', emoji: '🪐', label: 'Planet' },
      { id: 'rainbow', emoji: '🌈', label: 'Rainbow' },
      { id: 'leaf', emoji: '🍃', label: 'Leaf' },
      { id: 'snowflake', emoji: '❄️', label: 'Snow' },
      { id: 'heart', emoji: '💜', label: 'Heart' },
      { id: 'eye', emoji: '👁️', label: 'Eye' },
      { id: 'mushroom', emoji: '🍄', label: 'Mushroom' },
      { id: 'ghost', emoji: '👻', label: 'Ghost' },
      { id: 'dragon', emoji: '🐉', label: 'Dragon' },
      { id: 'crystal', emoji: '🔮', label: 'Crystal' },
      { id: 'fox', emoji: '🦊', label: 'Fox' },
      { id: 'owl', emoji: '🦉', label: 'Owl' },
      { id: 'butterfly', emoji: '🦋', label: 'Butterfly' },
      { id: 'penguin', emoji: '🐧', label: 'Penguin' },
      { id: 'volcano', emoji: '🌋', label: 'Volcano' },
      { id: 'tornado', emoji: '🌪️', label: 'Tornado' },
      { id: 'robot', emoji: '🤖', label: 'Robot' },
      { id: 'alien', emoji: '👽', label: 'Alien' },
      { id: 'ninja', emoji: '🥷', label: 'Ninja' },
      { id: 'crown', emoji: '👑', label: 'Crown' },
      { id: 'dice', emoji: '🎲', label: 'Dice' },
      { id: 'target', emoji: '🎯', label: 'Target' },
      { id: 'trophy', emoji: '🏆', label: 'Trophy' },
      { id: 'key', emoji: '🗝️', label: 'Key' },
      { id: 'wand', emoji: '🪄', label: 'Magic Wand' },
      { id: 'unicorn', emoji: '🦄', label: 'Unicorn' },
      { id: 'swords', emoji: '⚔️', label: 'Swords' },
      { id: 'shield', emoji: '🛡️', label: 'Shield' },
      { id: 'ufo', emoji: '🛸', label: 'UFO' },
      { id: 'sun', emoji: '☀️', label: 'Sun' },
      { id: 'compass', emoji: '🧭', label: 'Compass' },
      { id: 'hourglass', emoji: '⏳', label: 'Hourglass' },
    ],
  },
  animals: {
    key: 'animals',
    name: 'Wild Safari',
    icon: '🐾',
    cardBack: '🌿',
    color: '#48bb78',
    glow: 'rgba(72,187,120,0.3)',
    border: 'rgba(72,187,120,0.45)',
    symbols: [
      { id: 'lion', emoji: '🦁', label: 'Lion' },
      { id: 'tiger', emoji: '🐯', label: 'Tiger' },
      { id: 'panda', emoji: '🐼', label: 'Panda' },
      { id: 'fox_a', emoji: '🦊', label: 'Fox' },
      { id: 'koala', emoji: '🐨', label: 'Koala' },
      { id: 'unicorn_a', emoji: '🦄', label: 'Unicorn' },
      { id: 'dolphin', emoji: '🐬', label: 'Dolphin' },
      { id: 'eagle', emoji: '🦅', label: 'Eagle' },
      { id: 'owl_a', emoji: '🦉', label: 'Owl' },
      { id: 'octopus', emoji: '🐙', label: 'Octopus' },
      { id: 'butterfly_a', emoji: '🦋', label: 'Butterfly' },
      { id: 'flamingo', emoji: '🦩', label: 'Flamingo' },
      { id: 'hedgehog', emoji: '🦔', label: 'Hedgehog' },
      { id: 'giraffe', emoji: '🦒', label: 'Giraffe' },
      { id: 'zebra', emoji: '🦓', label: 'Zebra' },
      { id: 'turtle', emoji: '🐢', label: 'Turtle' },
      { id: 'penguin_a', emoji: '🐧', label: 'Penguin' },
      { id: 'peacock', emoji: '🦚', label: 'Peacock' },
      { id: 'seal', emoji: '🦭', label: 'Seal' },
      { id: 'wolf', emoji: '🐺', label: 'Wolf' },
      { id: 'raccoon', emoji: '🦝', label: 'Raccoon' },
      { id: 'frog', emoji: '🐸', label: 'Frog' },
      { id: 'monkey', emoji: '🐵', label: 'Monkey' },
      { id: 'bee', emoji: '🐝', label: 'Bee' },
      { id: 'crab', emoji: '🦀', label: 'Crab' },
      { id: 'shark', emoji: '🦈', label: 'Shark' },
      { id: 'crocodile', emoji: '🐊', label: 'Crocodile' },
      { id: 'leopard', emoji: '🐆', label: 'Leopard' },
      { id: 'deer', emoji: '🦌', label: 'Deer' },
      { id: 'kangaroo', emoji: '🦘', label: 'Kangaroo' },
      { id: 'llama', emoji: '🦙', label: 'Llama' },
      { id: 'squirrel', emoji: '🐿️', label: 'Squirrel' },
      { id: 'sloth', emoji: '🦥', label: 'Sloth' },
      { id: 'otter', emoji: '🦦', label: 'Otter' },
      { id: 'skunk', emoji: '🦨', label: 'Skunk' },
      { id: 'badger', emoji: '🦡', label: 'Badger' },
      { id: 'elephant', emoji: '🐘', label: 'Elephant' },
      { id: 'rhino', emoji: '🦏', label: 'Rhino' },
      { id: 'turkey', emoji: '🦃', label: 'Turkey' },
      { id: 'dove', emoji: '🕊️', label: 'Dove' },
    ],
  },
  snacks: {
    key: 'snacks',
    name: 'Snack Attack',
    icon: '🍕',
    cardBack: '🍩',
    color: '#ed8936',
    glow: 'rgba(237,137,54,0.3)',
    border: 'rgba(237,137,54,0.45)',
    symbols: [
      { id: 'pizza', emoji: '🍕', label: 'Pizza' },
      { id: 'burger', emoji: '🍔', label: 'Burger' },
      { id: 'fries', emoji: '🍟', label: 'Fries' },
      { id: 'sushi', emoji: '🍣', label: 'Sushi' },
      { id: 'taco', emoji: '🌮', label: 'Taco' },
      { id: 'donut', emoji: '🍩', label: 'Donut' },
      { id: 'icecream', emoji: '🍦', label: 'Ice Cream' },
      { id: 'croissant', emoji: '🥐', label: 'Croissant' },
      { id: 'avocado', emoji: '🥑', label: 'Avocado' },
      { id: 'strawberry', emoji: '🍓', label: 'Strawberry' },
      { id: 'popcorn', emoji: '🍿', label: 'Popcorn' },
      { id: 'cookie', emoji: '🍪', label: 'Cookie' },
      { id: 'pancake', emoji: '🥞', label: 'Pancake' },
      { id: 'ramen', emoji: '🍜', label: 'Ramen' },
      { id: 'watermelon', emoji: '🍉', label: 'Watermelon' },
      { id: 'cheese', emoji: '🧀', label: 'Cheese' },
      { id: 'hotdog', emoji: '🌭', label: 'Hot Dog' },
      { id: 'pretzel', emoji: '🥨', label: 'Pretzel' },
      { id: 'sandwich', emoji: '🥪', label: 'Sandwich' },
      { id: 'burrito', emoji: '🌯', label: 'Burrito' },
      { id: 'falafel', emoji: '🥙', label: 'Pita' },
      { id: 'dumpling', emoji: '🥟', label: 'Dumpling' },
      { id: 'shrimp', emoji: '🍤', label: 'Tempura' },
      { id: 'riceball', emoji: '🍙', label: 'Onigiri' },
      { id: 'cake', emoji: '🍰', label: 'Cake' },
      { id: 'cupcake', emoji: '🧁', label: 'Cupcake' },
      { id: 'chocolate', emoji: '🍫', label: 'Chocolate' },
      { id: 'candy', emoji: '🍬', label: 'Candy' },
      { id: 'lollipop', emoji: '🍭', label: 'Lollipop' },
      { id: 'custard', emoji: '🍮', label: 'Custard' },
      { id: 'honey', emoji: '🍯', label: 'Honey' },
      { id: 'grapes', emoji: '🍇', label: 'Grapes' },
      { id: 'apple', emoji: '🍎', label: 'Apple' },
      { id: 'banana', emoji: '🍌', label: 'Banana' },
      { id: 'pineapple', emoji: '🍍', label: 'Pineapple' },
      { id: 'peach', emoji: '🍑', label: 'Peach' },
      { id: 'cherries', emoji: '🍒', label: 'Cherries' },
      { id: 'mango', emoji: '🥭', label: 'Mango' },
      { id: 'coconut', emoji: '🥥', label: 'Coconut' },
      { id: 'kiwi', emoji: '🥝', label: 'Kiwi' },
    ],
  },
  hearts: {
    key: 'hearts',
    name: 'Sweet Hearts',
    icon: '💖',
    cardBack: '💌',
    color: '#f06292',
    glow: 'rgba(240,98,146,0.3)',
    border: 'rgba(240,98,146,0.45)',
    symbols: [
      { id: 'sparkle_heart', emoji: '💖', label: 'Sparkle Heart' },
      { id: 'ribbon_heart', emoji: '💝', label: 'Gift Heart' },
      { id: 'two_hearts', emoji: '💕', label: 'Two Hearts' },
      { id: 'sweet_cupcake', emoji: '🧁', label: 'Cupcake' },
      { id: 'sweet_lollipop', emoji: '🍭', label: 'Lollipop' },
      { id: 'pink_ribbon', emoji: '🎀', label: 'Ribbon' },
      { id: 'teddy_bear', emoji: '🧸', label: 'Teddy Bear' },
      { id: 'shortcake', emoji: '🍰', label: 'Shortcake' },
      { id: 'cherry_blossom', emoji: '🌸', label: 'Cherry Blossom' },
      { id: 'berry', emoji: '🍓', label: 'Strawberry' },
      { id: 'sweet_candy', emoji: '🍬', label: 'Sweet Candy' },
      { id: 'choco_bar', emoji: '🍫', label: 'Chocolate' },
      { id: 'boba_tea', emoji: '🧋', label: 'Boba Tea' },
      { id: 'shaved_ice', emoji: '🍧', label: 'Shaved Ice' },
      { id: 'mirror', emoji: '🪞', label: 'Mirror' },
      { id: 'pink_gem', emoji: '💎', label: 'Diamond' },
      { id: 'love_letter', emoji: '💌', label: 'Love Letter' },
      { id: 'rose', emoji: '🌹', label: 'Rose' },
      { id: 'bouquet', emoji: '💐', label: 'Bouquet' },
      { id: 'tiara', emoji: '👑', label: 'Crown' },
      { id: 'winged_horse', emoji: '🦄', label: 'Unicorn' },
      { id: 'ring', emoji: '💍', label: 'Ring' },
      { id: 'pinata', emoji: '🪅', label: 'Piñata' },
      { id: 'doll', emoji: '🪆', label: 'Matryoshka' },
      { id: 'swan', emoji: '🦢', label: 'Swan' },
      { id: 'pink_flamingo', emoji: '🦩', label: 'Flamingo' },
      { id: 'lotus', emoji: '🪷', label: 'Lotus' },
      { id: 'hibiscus', emoji: '🌺', label: 'Hibiscus' },
      { id: 'tulip', emoji: '🌷', label: 'Tulip' },
      { id: 'ballet_shoes', emoji: '🩰', label: 'Ballet' },
      { id: 'clutch', emoji: '👝', label: 'Clutch' },
      { id: 'lipstick', emoji: '💄', label: 'Lipstick' },
      { id: 'kiss', emoji: '💋', label: 'Kiss' },
      { id: 'cheers', emoji: '🥂', label: 'Cheers' },
      { id: 'sundae', emoji: '🍨', label: 'Sundae' },
      { id: 'bday_cake', emoji: '🎂', label: 'Birthday Cake' },
      { id: 'moon_cake', emoji: '🥮', label: 'Mooncake' },
      { id: 'dango', emoji: '🍡', label: 'Dango' },
      { id: 'fish_cake', emoji: '🍥', label: 'Naruto' },
      { id: 'juice_box', emoji: '🧃', label: 'Juice Box' },
    ],
  },
  space: {
    key: 'space',
    name: 'Cosmic Galaxy',
    icon: '🚀',
    cardBack: '🪐',
    color: '#4fd1c5',
    glow: 'rgba(79,209,197,0.3)',
    border: 'rgba(79,209,197,0.45)',
    symbols: [
      { id: 'rocket', emoji: '🚀', label: 'Rocket' },
      { id: 'saturn', emoji: '🪐', label: 'Saturn' },
      { id: 'flying_saucer', emoji: '🛸', label: 'UFO' },
      { id: 'alien_monster', emoji: '👾', label: 'Alien' },
      { id: 'milky_way', emoji: '🌌', label: 'Galaxy' },
      { id: 'shooting_comet', emoji: '☄️', label: 'Comet' },
      { id: 'satellite', emoji: '🛰️', label: 'Satellite' },
      { id: 'full_moon', emoji: '🌕', label: 'Moon' },
      { id: 'telescope', emoji: '🔭', label: 'Telescope' },
      { id: 'astronaut', emoji: '🧑‍🚀', label: 'Astronaut' },
      { id: 'shooting_star', emoji: '🌠', label: 'Meteor' },
      { id: 'sun_star', emoji: '☀️', label: 'Sun' },
      { id: 'glowing_star', emoji: '🌟', label: 'Glow Star' },
      { id: 'plasma_orb', emoji: '🔮', label: 'Plasma' },
      { id: 'cosmic_ray', emoji: '⚡', label: 'Cosmic Ray' },
      { id: 'space_bot', emoji: '🤖', label: 'Droid' },
      { id: 'new_moon', emoji: '🌑', label: 'Dark Moon' },
      { id: 'crescent_moon', emoji: '🌓', label: 'Half Moon' },
      { id: 'waxing_moon', emoji: '🌔', label: 'Gibbous' },
      { id: 'earth_americas', emoji: '🌍', label: 'Earth' },
      { id: 'earth_asia', emoji: '🌏', label: 'Earth Asia' },
      { id: 'sparkles_space', emoji: '✨', label: 'Stardust' },
      { id: 'dizzy_star', emoji: '💫', label: 'Orbit' },
      { id: 'supernova', emoji: '💥', label: 'Supernova' },
      { id: 'cyclone_nebula', emoji: '🌀', label: 'Nebula' },
      { id: 'sun_glasses', emoji: '🕶️', label: 'Visor' },
      { id: 'antenna', emoji: '📡', label: 'Antenna' },
      { id: 'ion_battery', emoji: '🔋', label: 'Ion Cell' },
      { id: 'spectroscope', emoji: '🔬', label: 'Scope' },
      { id: 'antimatter', emoji: '🧪', label: 'Antimatter' },
      { id: 'atom_core', emoji: '⚛️', label: 'Atom' },
      { id: 'black_hole', emoji: '🕳️', label: 'Black Hole' },
      { id: 'space_compass', emoji: '🧭', label: 'Nav Compass' },
      { id: 'space_time', emoji: '⏳', label: 'Spacetime' },
      { id: 'shield_matrix', emoji: '🛡️', label: 'Deflector' },
      { id: 'beacon', emoji: '🌐', label: 'Beacon' },
      { id: 'laser_sword', emoji: '⚔️', label: 'Laser' },
      { id: 'asteroid', emoji: '🪨', label: 'Asteroid' },
      { id: 'pulsar', emoji: '⭐', label: 'Pulsar' },
      { id: 'hyperspace', emoji: '🌈', label: 'Hyperspace' },
    ],
  },
  fantasy: {
    key: 'fantasy',
    name: 'Fantasy Quest',
    icon: '⚔️',
    cardBack: '🛡️',
    color: '#9f7aea',
    glow: 'rgba(159,122,234,0.3)',
    border: 'rgba(159,122,234,0.45)',
    symbols: [
      { id: 'swords_f', emoji: '⚔️', label: 'Swords' },
      { id: 'shield_f', emoji: '🛡️', label: 'Shield' },
      { id: 'crown_f', emoji: '👑', label: 'Crown' },
      { id: 'dragon_f', emoji: '🐉', label: 'Dragon' },
      { id: 'magic_wand', emoji: '🪄', label: 'Wand' },
      { id: 'bow_arrow', emoji: '🏹', label: 'Bow' },
      { id: 'spell_scroll', emoji: '📜', label: 'Scroll' },
      { id: 'dungeon_key', emoji: '🗝️', label: 'Key' },
      { id: 'potion_bottle', emoji: '🧪', label: 'Potion' },
      { id: 'castle_tower', emoji: '🏰', label: 'Castle' },
      { id: 'mana_gem', emoji: '💎', label: 'Gem' },
      { id: 'wizard_hat', emoji: '🧙', label: 'Wizard' },
      { id: 'griffin_eagle', emoji: '🦅', label: 'Griffin' },
      { id: 'pegasus_unicorn', emoji: '🦄', label: 'Pegasus' },
      { id: 'gold_coin', emoji: '🪙', label: 'Coin' },
      { id: 'mystic_candle', emoji: '🕯️', label: 'Candle' },
      { id: 'dagger', emoji: '🗡️', label: 'Dagger' },
      { id: 'battle_axe', emoji: '🪓', label: 'Axe' },
      { id: 'trident', emoji: '🔱', label: 'Trident' },
      { id: 'scrying_orb', emoji: '🔮', label: 'Orb' },
      { id: 'war_horn', emoji: '📯', label: 'War Horn' },
      { id: 'urn_relic', emoji: '🏺', label: 'Relic' },
      { id: 'ruby_ring', emoji: '💍', label: 'Ring' },
      { id: 'prayer_beads', emoji: '📿', label: 'Amulet' },
      { id: 'temple_door', emoji: '🚪', label: 'Gate' },
      { id: 'astrolabe', emoji: '🧭', label: 'Astrolabe' },
      { id: 'treasure_map', emoji: '🗺️', label: 'Map' },
      { id: 'camp_tent', emoji: '⛺', label: 'Camp' },
      { id: 'ancient_golem', emoji: '🗿', label: 'Golem' },
      { id: 'tombstone', emoji: '🪦', label: 'Crypt' },
      { id: 'chess_king', emoji: '♟️', label: 'Pawn' },
      { id: 'wild_joker', emoji: '🃏', label: 'Joker' },
      { id: 'drama_masks', emoji: '🎭', label: 'Mask' },
      { id: 'phoenix_quill', emoji: '🪶', label: 'Quill' },
      { id: 'hourglass_f', emoji: '⏳', label: 'Chronos' },
      { id: 'holy_grail', emoji: '🏆', label: 'Chalice' },
      { id: 'fire_torch', emoji: '🔥', label: 'Torch' },
      { id: 'clover_luck', emoji: '🍀', label: 'Luck' },
      { id: 'crystal_skull', emoji: '💀', label: 'Skull' },
      { id: 'sun_emblem', emoji: '☀️', label: 'Sun Emblem' },
    ],
  },
  arcade: {
    key: 'arcade',
    name: 'Retro Arcade',
    icon: '🎮',
    cardBack: '🕹️',
    color: '#ed64a6',
    glow: 'rgba(237,100,166,0.3)',
    border: 'rgba(237,100,166,0.45)',
    symbols: [
      { id: 'joystick', emoji: '🕹️', label: 'Joystick' },
      { id: 'pixel_invader', emoji: '👾', label: 'Invader' },
      { id: 'gamepad', emoji: '🎮', label: 'Gamepad' },
      { id: 'lucky_dice', emoji: '🎲', label: 'Dice' },
      { id: 'puzzle_piece', emoji: '🧩', label: 'Puzzle' },
      { id: 'arcade_coin', emoji: '🪙', label: 'Coin' },
      { id: 'floppy_disk', emoji: '💾', label: 'Floppy' },
      { id: 'laser_disc', emoji: '💿', label: 'Disc' },
      { id: 'retro_tv', emoji: '📺', label: 'CRT TV' },
      { id: 'boombox', emoji: '📻', label: 'Radio' },
      { id: 'high_score_trophy', emoji: '🏆', label: 'Trophy' },
      { id: 'gold_medal', emoji: '🥇', label: 'Medal' },
      { id: 'hit_boom', emoji: '💥', label: 'Boom' },
      { id: 'turbo_bolt', emoji: '⚡', label: 'Turbo' },
      { id: 'bullseye_target', emoji: '🎯', label: 'Target' },
      { id: 'pixel_bomb', emoji: '💣', label: 'Bomb' },
      { id: 'bowling', emoji: '🎳', label: 'Bowling' },
      { id: 'ping_pong', emoji: '🏓', label: 'Ping Pong' },
      { id: 'skateboard', emoji: '🛹', label: 'Skate' },
      { id: 'turbo_racer', emoji: '🏎️', label: 'Racer' },
      { id: 'space_shuttle', emoji: '🚀', label: 'Blaster' },
      { id: 'arcade_mecha', emoji: '🤖', label: 'Mecha' },
      { id: 'synth_guitar', emoji: '🎸', label: 'Guitar' },
      { id: 'chiptune_keys', emoji: '🎹', label: 'Synth' },
      { id: 'dj_headphones', emoji: '🎧', label: 'Headphones' },
      { id: 'shades_8bit', emoji: '🕶️', label: 'Shades' },
      { id: 'tetris_brick', emoji: '🧱', label: 'Brick' },
      { id: 'checkered_flag', emoji: '🏁', label: 'Finish' },
      { id: 'star_badge', emoji: '🏅', label: 'Badge' },
      { id: 'arcade_ticket', emoji: '🎟️', label: 'Ticket' },
      { id: 'popcorn_tub', emoji: '🍿', label: 'Popcorn' },
      { id: 'circus_tent', emoji: '🎪', label: 'Carnival' },
      { id: 'pinball_flipper', emoji: '🪀', label: 'YoYo' },
      { id: 'kite', emoji: '🪁', label: 'Kite' },
      { id: 'magic_8ball', emoji: '🎱', label: '8-Ball' },
      { id: 'slot_machine', emoji: '🎰', label: 'Slots' },
      { id: 'neon_sign', emoji: '💡', label: 'Neon' },
      { id: 'firecracker', emoji: '🧨', label: 'Dynamite' },
      { id: 'ring_bell', emoji: '🔔', label: 'Jackpot Bell' },
      { id: 'red_flag', emoji: '🚩', label: 'Waypoint' },
    ],
  },
};

/**
 * Fisher-Yates shuffle
 */
function shuffle(array) {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/**
 * Create a shuffled deck of card objects based on difficulty and theme.
 * Each symbol appears exactly twice.
 * @param {'quick'|'easy'|'medium'|'hard'|'master'} difficulty
 * @param {string} themeKey
 * @returns {Card[]}
 */
export function createDeck(difficulty = 'easy', themeKey = 'classic') {
  const config = DIFFICULTY_CONFIG[difficulty] || DIFFICULTY_CONFIG.easy;
  const theme = THEMES[themeKey] || THEMES.classic;
  const numPairs = config.pairs;

  const chosenSymbols = theme.symbols.slice(0, numPairs);
  const pairs = chosenSymbols.flatMap((sym) => [
    { id: `${sym.id}-a`, pairId: sym.id, emoji: sym.emoji, label: sym.label, index: 0 },
    { id: `${sym.id}-b`, pairId: sym.id, emoji: sym.emoji, label: sym.label, index: 0 },
  ]);

  return shuffle(pairs).map((card, idx) => ({ ...card, index: idx }));
}

/**
 * Generate a 6-character alphanumeric room code.
 */
export function generateRoomCode() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  return Array.from({ length: 6 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
}

/**
 * Get grid column count for a difficulty level.
 * @param {'quick'|'easy'|'medium'|'hard'|'master'} difficulty
 * @returns {number}
 */
export function getGridCols(difficulty = 'easy') {
  return DIFFICULTY_CONFIG[difficulty]?.cols ?? 4;
}
